### ISSUE TITLE
V 2.1.1 not starting in Windows after Replacing PT Tracker main file

### ISSUE THREAD

**Issue by cryptomail2018** [bTayFla/PtTracker#153] opened 2018-05-31 03:31 UTC
when upgrade to new version the Pt Tracker CMD window not start when revert back to previous version V 2.1 it works 

something not right in new version

**Comment by clownfish44** [comment] 2018-05-31 03:33
Duplicate of #152

**Closed as completed by clownfish44** 2018-05-31 03:33 UTC
